### ISSUE TITLE
Saving more than 5 tattoos?

### ISSUE THREAD

**Issue by TobiasThaisen** [ESX-PUBLIC/esx_tattooshop#4] opened 2018-10-30 16:04 UTC
Can't save more than 5 tattoos beacuse of the VARCHAR limit to 250 letters. Anybody know a fix to this? Setting it to LONGTEXT will just give more problems in the console

**Comment by HawaiiBeach** [comment] 2018-10-30 18:09
Why wouldn't `LONGTEXT ` work?

**Comment by TobiasThaisen** [comment] 2018-10-30 21:42
Beacuse on LONGTEXT you can't set DEFAULT '{}'

**Comment by HawaiiBeach** [comment] 2018-10-30 22:24
You don't really need the default thing

**Comment by TobiasThaisen** [comment] 2018-10-31 06:39
If the default ain't there it's gonna throw alot of errors in the serversided console

**Comment by HawaiiBeach** [comment] 2018-10-31 13:57
Duplicate of #3

**Closed as completed by HawaiiBeach** 2018-10-31 13:57 UTC
Labels: duplicate
